### ISSUE TITLE
[ch.suedhang.apps.tmt_V3]  ::  Z-Graphik

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#5]
- Farben der klinischen Normen anpassen, da Farben nun kaum zu unterscheiden
- Die Grösse des angegeben Zahlenwertes auf die Schriftgrösse der anderen Angaben verkleinern
- für den Quotienten nur den Wert neben der Eintrittsgraphik bei Zeit und Fehler mit angeben und keine eigene Graphik

**Comment by ottigerb** [comment]
Klinikstichproben können nun elegant erstellt und Apps zur Verfügung gestellt werden. Diese Hürde ist somit gemeistert!  YES!    Entsprechend gehe ich nun die Überarbeitung von http://demo.optinomic.org/api/#/patient/1/stay/144/app/ch.suedhang.apps.tmt_V3 an.

### Vorschlag

Nach längeren Überlegungen bin ich zum Schluss gekommen, dass es deutlich mehr Sinn macht statt nach _TMT A_  und _TMT B_  nach dem Messzeitpunkt zu gruppieren. Also: _Eintritt_ ,  _Anderer Messzeitpunkt_ &  _Austritt_.  Dies hat m.E. viele Vorteile:
-  Klinikstichprobe kann über mehrere "Z-Werte" geteilt werden.
-  Auch dient dieses "Design" den Forderungen von  #7  (Bericht Eintritt / Austritt)

=> Ich werde dies in den nächsten Stunden angehen - falls nicht ein gut begründetes Veto kommt. 

### Issues im OP
1. Farbanpassung: Allenfalls nicht mehr nötig mit dem genannten Vorschlag. Auch wird bei einem S/W Druck (als PDF speichern) die Kraft der Farben eliminiert. Grafiken sollten weitgehend S/W-Fähig sein. 
2. Grösse des Z-Wertes:  Dieser wird nicht verkleinert. Gerade bei der Darstellung auf dem Mobile ist dies wichtig.
3.  Quotienten:  Perfekt.  Spricht ebenfalls für meinen Vorschlag. So kann die Gruppe Eintritt den Quotienten anzeigen.

### Z-Score Grafik

Wäre allenfalls der `mean` der Klinikstichprobe interessant?  Dieser könnte ebenfalls mit einer Vertikalen Linie dargestellt werden.

**Comment by SonjaKaufmann** [comment]
Zu dem Vorschlag:
Du meinst Eintritt: TMT A und TMT B und dann darunter Austritt TMT A und TMT B und ggf dazwischen andere Messzeitpunkte, oder?

VETO

Begründung folgt!

**Comment by ottigerb** [comment]
Genau, das war der Plan. Da bin ich gespannt auf das Veto.  :-)

**Comment by SonjaKaufmann** [comment]
Also das teilen der Z-WErte trifft nicht ganz zu. Zum einen haben wir in der Regel nur Eintritt und Austritt und keine anderen Werte, möchten die Option anderer Messzeitpunkte allerdings erhalten.
Der TMT A Eintritt und der TMT A Austritt haben zwar die gleiche gesunde Normstichprobe, aber verschiedene klinische Stichproben. Wir möchten ja damit vergleichen, wie jemand zu Beginn der Behandlung liegt und bei Abschluss möchten wir damit vergleichen, wie andere Patienten bei Abschluss  sind. Weiss nicht ob man dann mehrere Einzelblöcke machen kann, so das es mit #7 zusammengeht.

## ISSues in OP (was das auch immer heisst:
1. doch farbanpassungen sind weiter nötig, allerdings dann in gut unterscheidbaren Graustufen: Eine für Klinische Norm Eintritt und eine für klinische Norm Austritt
2. Wir stellen die Auswertungen nicht mobil dar und der Wert ist für das lesen der Graphik eigentlich unerheblich, denn das steckt im Hintergrund und Balkenverhältnis. Daher sollten die Graphiken sogar ohne Wert interpretiert werden können. Um die Therapeuten auf das essentielle der Graphiken und Interpretation zu lenken, ist der grosse Wert irritierend.

## Z-Score Graphik

nein, meines Erachtens nach braucht es das nicht. Wofür soll der wichtig sein?

**Comment by SonjaKaufmann** [comment]
Ausserdem kann man die Balken der Patienten schon vergleichen wenn sie direkt untereinander sind, sie bedeuten nur etwas anderes im Bezug zur klinischen Stichprobe zum Messzeitpunkt.
Also wenn ich TMT A Eintritt und TMT A Austritt untereinander habe, dann sehe ich auch wie sich der Patient verändert hat im Vergleich des Eintrittsbalken mit dem Austrittsbalken, da ja beide an der gesunden Norm normiert. Die unterschiedlichen Klinikstichproben zeigen mir an, wie sich die Patienten verändern.
Wenn ich die Graphiken von den Messzeitpunkten zu weit auseinander habe, dann gehen diese Informationen verloren. Daher wird es auch beim BSCL so sein, dann man Skala 1 Eintritt Austritt, Skala2 Eintritt Austritt, Skala 3 .....usw abbilden muss und nicht erst den ganzen Eintritt und dann den ganzen Austritt. Das siehst Du auch in den Skizzen zu den BSCL-Graphiken. Wenn wir keine Darstellung der Differenzwerte machen wollen, dann muss die Veränderung mit dem Auge erfasst werden können und das geht nur, wenn es direkt untereinander dargestellt ist.

**Comment by ottigerb** [comment]
**Anmerkungen**
OP = Opening Post |  der erste Eintrag des Issues.  Idealerweise wird der OP durch den "Ersteller" aktuell gehalten - falls das Issue resp. deren Kommentare lange ist / wird.  Auch gilt es zu beachten, dass ein Issue geschlossen werden kann. Also nicht: "Frieden auf der Welt" - da dies wohl leider nie geschlossen werden kann.

**Zum Topic**

OK, ich nehme dies mal so an und  lass mal etwas "Hirnschmalz" grübeln. Für mich wäre folgende Darstellung irgendwie logischer und direkter mit der Messung verbunden.

#### Eintritt
- TMT A  |  Normstichprobe von der Patient-Calculation
- TMT B  |  Normstichprobe von der Patient-Calculation  
  =>  Beide teilen sich die Klinikstichprobe Eintritt

#### Anderer
- TMT A  |  Normstichprobe von der Patient-Calculation
- TMT B  |  Normstichprobe von der Patient-Calculation  
  =>  Beide teilen sich die Klinikstichprobe Anderer

#### Austritt
- TMT A  |  Normstichprobe von der Patient-Calculation
- TMT B  |  Normstichprobe von der Patient-Calculation  
  =>  Beide teilen sich die Klinikstichprobe Austritt

Allenfalls liesse sich eine Verbesserungsdarstellung finden. Falls Eintritt & Austritt vorhanden ist:
- TMT A:  Bei Austritt 0.8 Z-Wert Punkte besser als bei Eintritt
- TMT B:  Bei Austritt 1.8 Z-Wert Punkte besser als bei Eintritt

Wäre so nicht #7 sichergestellt und für die Verbesserungs-Übersicht wurde ebenfalls gesorgt?

**Comment by SonjaKaufmann** [comment]
Ja es ist so, in der Regel basieren die Z-Werte auf der Normstichprobe und das sind immer Gesunde zum Eintrittszeitpunkt. Selten gibt es Normwerte für Gesunde nach einer Behandlung. Von daher beruhen die Balken immer auf der Verrechnung des Patientenwertes mit der gesunden Norm.  und daher kann man auch die Werte von Z-Werte von Eintritt und Austritt des Patienten miteinander vergleichen, da sie mit der gleichen Norm, dem gleichen Mass errechnet/gemessen wurden. Was sich aber unterscheidet ist, was der Z-Wert im Vergleich zu anderen Patienten bedeutet und das wird durch die klinische Norm im Hintergrund deutlich.
Man kann noch eine zusätzliche Darstellung der Veränderung machen und müsste dann noch klinische Veränderungsnormen berechnen, ja das ist möglich, aber diese wären dann in Einheiten der Normstichprobe und da wird mir dann langsam sturm im Kopf. Und das muss man dann ja auch noch dem Patietenten erklären.

**Comment by SonjaKaufmann** [comment]
Vielleicht wäre ja eine Darstellung nebeneinander möglich?

**Comment by ottigerb** [comment]
Jaaaa - gute Idee!  Denn das "Gute" liegt oft soooo Nahe!  :-)

**Comment by SonjaKaufmann** [comment]
Dann hätte man nicht so ein Streifenhörnchen im Hintergrund, weil sich die klinischen Ein- und Austrittsnormen immer abwechseln und könnte immer noch das Auge für den Vergleich der Werte nutzen.

**Comment by SonjaKaufmann** [comment]
Allerdings wird es dann wieder mit den Beschriftungen sehr knapp und man müsste doppelt beschriften, das ist auch nicht gut oder gar übersichtlich. Dann doch eher Streifenhörnchen als mangelnder Text!

**Comment by ottigerb** [comment]
### Aktueller Stand

http://demo.optinomic.org/api/#/patient/387/stay/43/app/ch.suedhang.apps.tmt_V3

![bildschirmfoto 2016-10-21 um 16 26 39](https://cloud.githubusercontent.com/assets/2470873/19601853/376017c6-97ab-11e6-961f-d319764a7a52.png)

Nachdem der Button `Brille` angeklickt wird, verfügt jedes Z-Score über einen Klinikstichproben / Browser  -   somit kann 'schnell und unkompliziert' mit anderen Patientengruppen verglichen werden.   **NICE**!

### Klinikstichproben / Browser

![bildschirmfoto 2016-10-21 um 16 28 14](https://cloud.githubusercontent.com/assets/2470873/19601933/82e0b4bc-97ab-11e6-8037-73feb55e380c.png)

### ToDo's

Haken = erledigt
- [X] Farben: Klinikstichprobe (KS)
- [x] Farbe: Rot / Grün wenn über resp. unter der KS liegt.
- [x] Zahlenwert: Schriftgrösse & Z-Score Grafik Tweaks
- [x] Something more?

**Comment by SonjaKaufmann** [comment]
Also in den eingefügten Abbildungen sind die Farben der KS und die Rot/grün Sache noch nicht drin!
Hatten wir nicht gesagt, erst Eintritt, dann Austritt? Da man ja von oben nach unten liest. Sprich die Reihenfolge aufsteigend mit dem Datum. Bin da nicht mehr sicher.
Wenn ich auf den Link gehe oder auch wenn ich unter Patient Ottiger auf TMT V3 gehe, dann erscheint bei mir keine Graphik mehr. Mhhh, läuft irgendwie noch nicht. Obwohl es sich vom dargestellten und beschriebenen Entwicklungsstand gut anhört.

**Comment by ottigerb** [comment]
Daten - Reihenfolge:  Zeitlich:  früh -> spät

**Comment by ottigerb** [comment]
Kliniksp :  Mitte - schmaler Strich.

**Comment by ottigerb** [comment]
Z-Score Grafiken gemäss Besprechung angepasst:
1. Mean der Klinikstichprobe
2. Klinikstichprobe Begrenzung | Höhe nur bis "Basislinie"
3. Schriftgrössen angeglichen (Text left/right)
4. Z-Score Wert | Schriftgrösse verkleinert
5. TMT :: Keine Zeitangabe

![bildschirmfoto 2016-10-31 um 13 42 09](https://cloud.githubusercontent.com/assets/2470873/19854557/dc019b26-9f6f-11e6-837a-4febc5cd0951.png)

**Comment by schoenenb** [comment]
Ich erlaube mir, dieses Issue nochmals zu öffnen, da noch ein paar Sachen offen sind:
- [x] Daten-Reihenfolge: früh = top /spät = bottom
- [x] Legende für die Vergleichsstichprobe oberhalb der Daten oder nur bei TMT A
- [x] Striche bei Wertangaben (ausser 0) weglassen
- [x] dafür den weissen Strich für den Mean der Vergleichsstichprobe etwa in der Breite + Farbe wie jetzt bei den Wertangaben

**Comment by ottigerb** [comment]
Sortierung funktioniert wie gewünscht - hat 'Haare' gekostet!  Legende ist per 'default' @ Top:

![bildschirmfoto 2016-11-04 um 14 26 05](https://cloud.githubusercontent.com/assets/2470873/20007040/c3569e9a-a29a-11e6-80cd-b29af58b99dd.png)

Sobald eine Klinikstichprobe angepasst wird - werden die einzelnen "Klinikstichproben" innerhalb der Gruppen (TMT A / TMT B) angezeigt.  Dies, da die "Generelle Anzeige @ Top" nicht mehr stimmen könnte.  Denke eine gute Lösung gefunden zu haben.

![bildschirmfoto 2016-11-04 um 14 26 27](https://cloud.githubusercontent.com/assets/2470873/20007041/c36bb780-a29a-11e6-98c3-666b50324850.png)

Stiche-Tuning later!

**Comment by SonjaKaufmann** [comment]
Lieber Beat, ich öffne den Task wieder und wäre froh, wenn es um solche Task geht, wenn wir die gemeinsam schliessen könnten, bzw. eine Abnahme des Endstandes machen könnten. Hier sind aber für mich noch ein paar Punkte unklar.
- Also wenn ich bei Ottiger Patient schaue, dann stimmt die Reihenfolge wieder nicht!
- Der neue Mittelstrich ist drin, super
- Die Hintergrundfarben sind noch nicht so gewählt, dass sie auf einem schwarz-weiss-Ausdruck zu unterscheiden wären.
- Wozu ist das Glühbirnli da, wenn die Normierungsstichproben doch oben angegeben sind!

**Comment by ottigerb** [comment]
Reihenfolge - Bug:  Ottiger Patient hat unterschiedliche Fragebögen am Start. Unser ng-survey  hat kein `date`.  Werde ich noch einbauen.
- [x] `date` field | Erfassungsdatum in ng-survey einbauen.

**Comment by ottigerb** [comment]
**Reihenfolge**
Ich sehe kein Bug in der Reihenfolge:

![bildschirmfoto 2016-11-18 um 08 32 55](https://cloud.githubusercontent.com/assets/2470873/20422273/aa8aeef0-ad69-11e6-93c7-c019c42437eb.png)

=>  Sind allenfalls Browser-Unterschiede am Werk?  Sortiert es bei Euch anders? Dachte solchen Effekt hatten wir mal.

**Hintergrundfarbe**
Kann hier gesetzt werden:
https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.tmt_V3/main.js#L219

**Comment by SonjaKaufmann** [comment]
Irgendwie verstehen wir uns hier wohl nicht richtig. Wir wollten doch erst den Eintrittswert und dann den Austrittswert. In deiner letzten eingefügten Abbildung ist der Austritt oben! Oder sieht das Bild bei Dir anders aus?

- [x] Reihenfolge zeitlich aufsteigend

- [x] Farben für die klinischen Stichproben so, dass man sie auch in schwarz-weiss Ausdruck unterscheiden könnte

**Comment by ottigerb** [comment]
Die Reihenfolge bezieht sich auf das das Datum!

**Comment by SonjaKaufmann** [comment]
Ja aber in der Abbildung ist der Austritt am 3.11 und der Eintritt am 6.10 und nach meiner Zeitrechnung wäre das vorher. Aber jetzt sehe ich, dass der Eintritt im 2016 ist und der Austritt im 2015. So stimmt die Reihenfolge nach Datum natürlich, aber es ist ja unlogisch das ein Fall im 2015 Austritt, wenn er erst im 2016 eintritt. Also Logikfehler im Testfall und wahrscheinlich nicht in der Graphikausgabe, oder?

**Comment by ottigerb** [comment]
Genau - Testdaten wurde 'willkürlich' erfasst bzgl. Eintritt/Austritt.

**Comment by ottigerb** [comment]
Close issue ::  Sehe keine offenen Punkte hier.
