### ISSUE TITLE
[Optinomic]  Export-Toolbox

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#9]
http://demo.optinomic.org/api/#/admin/tools/export
### Ziel

Selektion von "Ausgangs-App" und danach gemäss folgendem Bild exportieren:  
### Hinweis

Die Export-Toolbox verlangt ein `[sql_init]` des bestehenden Moduls - vgl.:
https://doc.optinomic.org/V2/Developers/app_spezifikation.html#sqlinit-optional-can-have-many

![bildschirmfoto 2016-10-19 um 13 12 11](https://cloud.githubusercontent.com/assets/2470873/19516733/b041b4ba-95fd-11e6-8f0e-c0516beb5191.png)

**Comment by SonjaKaufmann** [comment]
Wie schon mal geschrieben (vielleicht untergegangen) fände ich es besser, wenn man das Datum eingeben könnte. Da man häufig ein Zeitfenster von einen Jahr braucht ist es leichter einzutippen als in dem wahrlich schicken Kalender zu scrollen.
Hey, die Anleitung ist ja englisch und für mich nicht verständlich. 
Wie soll das nun sein? Muss man immer noch den SQL-Code für den jeweiligen Fragebogen (App) angeben oder kann man sagen welcher Fragebogenergebnisse man möchte z.B. BSCL und es spielt dann automatisch den hinterlegten BSCL-SQL-Code rein und man hat nichts mehr mit dem Code zu tun, wenn er hinterlegt wurde. Oder drückt wählt man BSCL aus und dann erscheint der zugehörige Code im SQL-Fenster und man kann noch modifikationen vornehmen, wenn man z-B. nur einen bestimmten Patienten will? Denke die Exportsyntaxen weiter aus einem Wordfile reinkopieren zu müssen ist nicht die schönste Lösung.

**Comment by ottigerb** [comment]
Datumeingabe:  OK!

Genau:  Selektion von z.B. "BSCL" und dann gemäss Bild. Der SQL-Code kann bei Bedarf verändert werden - doch nicht nötig.   Kopiert muss nix werden.

**Comment by SonjaKaufmann** [comment]
Aha, das hört sich gut an. Wo wählt man denn den FB bzw. die App aus?

**Comment by ottigerb** [comment]
### Frage bzgl. den Falltypen

Wir haben ja folgende Falltypen, welche es beim Export zu bestimmen gilt:

``` JSON
[
  {
    "id": 0,
    "typ": "Alle",
    "name": "Alle Messungen im Erhebungszeitraum ausgeben"
  },
  {
    "id": 1,
    "typ": "A1",
    "name": "Ein- und Austritt im Erhebungszeitraum"
  },
  {
    "id": 2,
    "typ": "A2",
    "name": "Einritt vor Erhebungszeitraum und Austritt im Erhebungszeitraum"
  },
  {
    "id": 3,
    "typ": "B",
    "name": "Einritt im Erhebungszeitraum und Austritt nach Erhebungszeitraum"
  },
  {
    "id": 4,
    "typ": "C",
    "name": "Eintritt vor Erhebungszeitraum und Austritt nach Erhebungszeitraum"
  }
]
```

Die Frage lautet nun, wie soll mit 'verfahren' werden, wenn der "Austritt" noch nicht festgelegt, also unbekannt ist?

**Vorschlag**
Soll ein weiterer Typ hinzugefügt werden?

``` JSON
[
  {
    "id": 5,
    "typ": "D1",
    "name": "Einritt vor Erhebungszeitraum und Austritt unbekannt"
  },
  {
    "id": 6,
    "typ": "D2",
    "name": "Einritt im Erhebungszeitraum und Austritt unbekannt"
  }
]
```

**Comment by ottigerb** [comment]
**Erfolg:**  Falltyp (inkl. D1/D2) und Erhebungszeitraum funktioniert.
=>  Jetzt kann http://demo.optinomic.org/api/#/admin/tools/export 'verdrahtet' werden.  :-)

``` SQL
SELECT

  CASE WHEN ((stay.stop IS NULL) AND (stay.start NOT BETWEEN '2015-01-01' AND '2015-12-31')) THEN 'D1' ELSE CASE WHEN ((stay.stop IS NULL) AND (stay.start BETWEEN '2015-01-01' AND '2015-12-31')) THEN 'D2' ELSE CASE WHEN (stay.start IS NULL AND stay.stop IS NULL) THEN '?' ELSE 
    CASE WHEN (stay.start BETWEEN '2015-01-01' AND '2015-12-31') THEN 
       CASE WHEN (stay.stop BETWEEN '2015-01-01' AND '2015-12-31') THEN 'A1' ELSE 'B' END
       ELSE 
       CASE WHEN (stay.stop BETWEEN '2015-01-01' AND '2015-12-31') THEN 'A2' ELSE 'C' END
       END 
  END END END as optinomic_falltyp,
  *

FROM ch_suedhang_apps_actinfo_ein.actinfo_ein_view as d
LEFT JOIN stay ON(d.optinomic_stay_id = stay.id) 

WHERE d.optinomic_survey_filled BETWEEN '2015-01-01' AND '2015-12-31';
```

Resp.:

``` SQL
SELECT 
  *

FROM ch_suedhang_apps_actinfo_ein.actinfo_ein_view as d
LEFT JOIN stay ON(d.optinomic_stay_id = stay.id) 

WHERE 
   d.optinomic_survey_filled BETWEEN '2015-01-01' AND '2015-12-31'
AND 
  CASE WHEN ((stay.stop IS NULL) AND (stay.start NOT BETWEEN '2015-01-01' AND '2015-12-31')) THEN 'D1' ELSE CASE WHEN ((stay.stop IS NULL) AND (stay.start BETWEEN '2015-01-01' AND '2015-12-31')) THEN 'D2' ELSE CASE WHEN (stay.start IS NULL AND stay.stop IS NULL) THEN '?' ELSE 
    CASE WHEN (stay.start BETWEEN '2015-01-01' AND '2015-12-31') THEN 
       CASE WHEN (stay.stop BETWEEN '2015-01-01' AND '2015-12-31') THEN 'A1' ELSE 'B' END
       ELSE 
       CASE WHEN (stay.stop BETWEEN '2015-01-01' AND '2015-12-31') THEN 'A2' ELSE 'C' END
       END 
  END END END = 'A1'

LIMIT 10
```

Aktuell für:
- actInfo Eintritt
- actInfo Austritt
- AUS

=>  Weitere Module können nach deren 'Vorlage' jederzeit folgen.

**Comment by SonjaKaufmann** [comment]
Eigentlich sind es keine weiteren Falltypen, denn wenn der Austritt noch unbekannt ist, dann ist der Austritt nicht im Erhebungszeitraum. Wir machen ja keine Exporte die in der Zukunft liegen. Also wären die Fälle für mich Untergruppen der anderen Fälle, wo noch kein Austritt stattgefunden hat, also B und C.

**Comment by ottigerb** [comment]
OK - Danke!

**Comment by ottigerb** [comment]
Unsere Export-Toolbox funktioniert:  Yes!
http://demo.optinomic.org/api/#/admin/tools/export

Danke für Feedback!

Allenfalls liesse sich der "Joghurt-Export-User" noch "erquicken" von:
- Nachdem "jetzt ausführen" gewählt wurde - ein "Loading Spinner" zeigen. Im Sinne von - nur Geduld.
- Ein Switch hinzufügen:  Alle `optinomic_` Felder nicht exportieren.

**Comment by SonjaKaufmann** [comment]
Super läuft es, habe schon einen exportiert :-)
Fände es super, wenn es den switch gäbe, denn sonst muss man die rauslöschen und braucht sie ja gar nicht. Fände sogar besser man muss den switch einschalten, damit es die Optinomicfelder mit exportiert und sonst ist der Standard ohne Optinomicfelder.
Spinner sind immer gut, aber man sollte ja nicht mehr soooooooooooooooo lange warten müssen wie bei V1 oder?
Das mit der Datumseingabe zur Auswahl des Zeitraumes ist noch nicht umgesetzt, oder? Ich habe immer noch die schicken Kalender ;-)

**Comment by ottigerb** [comment]
http://demo.optinomic.org/api/#/admin/tools/export  sollte wie folgt aussehen:

![bildschirmfoto 2016-10-20 um 18 17 14](https://cloud.githubusercontent.com/assets/2470873/19568341/7bd406de-96f1-11e6-990d-34cdc403d6f1.png)

=>  Allenfalls abmelden und Login-Seite neu laden. Ein neuer Build ist der Zwischenzeit angekommen. Unter dem Optinomic-Logo unten rechts sollte nun Version: 7b76c16 stehen.

**Comment by SonjaKaufmann** [comment]
Also genau so finde ich es super!
Bei mir erscheint allerdings nicht diese Version (immer noch Kalender), obwohl unten die richtige Versionsnummer steht.
Vielleicht schaue ich mir dies Dienstag nochmal an, bin jetzt fertig mit arbeiten und im langen WE bis Dienstag!

**Comment by SonjaKaufmann** [comment]
Jetzt doch noch so gesehen, super super super!

**Comment by ottigerb** [comment]
#### ToDo:
- [ ]  `optinomic_` Felder nicht exportieren
- [x]  Doppelte Einträge z.B. bei HoNos eliminieren.

**Comment by SonjaKaufmann** [comment]
Kann man doppelte Einträge nicht besser markieren? Manchmal wird falsch eingegeben und man muss dann erst entscheiden welcher der richtige Datensatz ist und das geht besser mit Augenkontrolle als durch irgendwelche programmierten Entscheidungskriterien. Finde es aber eine sehr gute Idee!

**Comment by ottigerb** [comment]
Doppelte Einträge war wohl etwas 'verwirrlich' - damit meine ich lediglich:

<img width="685" alt="bildschirmfoto 2016-10-25 um 12 37 08" src="https://cloud.githubusercontent.com/assets/2470873/19682871/db582308-9aaf-11e6-80d1-c15808356ebc.png">

**Comment by SonjaKaufmann** [comment]
Muss die Datumsauswahl in YYYYMMTT formatiert sein? Kann man nicht ganz normal das Datum eingeben, sprich TT.MM.YYYY?

Das mit dem optinomic-Felder nicht exportieren wäre immer noch super!

Wie war das noch mit den Einstellungen für den Download? Wenn ich etwas exportiere, dann legt er es auf P: Google als csv ab. kann man das bei uns auch irgendwie so einstellen, dass er es im Excel auftut und einen anderen Speicherort angeben?

**Comment by ottigerb** [comment]
1.  **Datum**:  Genau, da wir ja kein "Datums-Picker" wollen:   Please enter a valid Date-Format: YYYY-MM-DD
2.  **optinomic_\*  Felder** nicht exportieren kommt noch.  Nicht so ganz ohne - hier muss ich zuerst die Abfrage starten und dann anstatt `SELECT *` die Felder aufführen welche nicht `optinomic_*` Felder sind.
3.  **Excel**: Sorry - hier habe ich keine Ahnung | Funktioniert auf dem Mac:  Sysadmin - Thömu anfragen.

**Comment by SonjaKaufmann** [comment]
1. Ja aber es gibt ja nicht nur die Wahl zwischen Picker und einen Format. Frage mich warum kein normales Datumsformat möglich ist, so wie wir in den Fragebogen-Intros auch das Datum "deutsch" angeben. Aber egal, dann halt kompliziert.
2. Super!
3. Gut, habe Frage an Thömu weitergeleitet.

Übrigens haben wir jetzt CHROME als Standardbrowser!

**Comment by schoenenb** [comment]
Kann man zu den Falltypen auch noch Gruppen hinzufügen, für die man dann Exporte machen kann? (Stichwort: Forschung)

**Comment by ottigerb** [comment]
Gruppen?  Patientengruppen?   Also z.B.: Exportiere alle "actInfo Eintritte" im Erhebungszeitraum X mit Falltyp A1 - von den Patienten, welche sich in der Gruppe "Sowiso" befinden?
=> Sicher möglich, doch ich müsste dies noch 'austüfteln'.  Bisher wurden Patientengruppen ausschliesslich via JS verarbeitet. Die Exporte sind ja reines SQL.  Ich mach mir hierzu mal "Hirnschmalz".

Zur Info: Es wurde Serverseitig bereits die Möglichkeit für Fallgruppen geschaffen, dies muss ich dann mal in den Client "übernehmen".

**Comment by schoenenb** [comment]
Ja genau, Patientengruppen.
Ich habe der Forschung vorgeschlagen, dass ich ihre Patienten bei Eintritt manuell in eine Gruppe einteile, auf welche sie dann sicher Zugriff haben. Sie brauchen nämlich gewisse Daten aus den Assessments. Statt alles zu exportieren und die benötigten Daten rauszusuchen müsste doch dann ein Export mit Beschränkung auf diese Gruppe möglich sein!?

**Comment by SonjaKaufmann** [comment]
Es ist noch offen:

- [x] Export ohne Optinomic-Felder

- [x] Das Datum in bei der Datumsauswahl im Format : TT.MM.YYYY

- [x] Manuelle Exportgruppen für Forschung nach Noras Idee

- [x] Export mit Pipes? Bei dem Export als csv werden bestimmte Felder mit Texteingaben und enthaltenen Simikolon und Kommata getrennt und alles andere verschiebt sich. Das ist ungünstig. Wäre es auch möglich wie früher im Export mit Pipes die Felder zu trennen?

 

 ohne

**Comment by ottigerb** [comment]
Export mit Pipes:  Kann unter TAB "Einstellungen" festgelegt werden.

**Comment by ottigerb** [comment]
### Patientengruppen
Die Export-Toolbox (http://demo.optinomic.org/api/#/admin/tools/export) kann ab sofort mit Patientengruppen (PG) umgehen. Wenn ein PG Filter gewählt wurde, werden nur Ergebnisse dieser Patienten exportiert:

![bildschirmfoto 2017-01-27 um 15 13 06](https://cloud.githubusercontent.com/assets/2470873/22373675/29ea3d02-e4a3-11e6-9cf8-e59bfe6c2697.png)

=>  Wird auf Südhang mit dem nächsten Stable Build verteilt. 

### Datumsformat
Das Datumsformat wird nicht umgestellt.  Die Daten liegen in diesem Format vor - alles andere wäre ein "gefährliches" - toDate() - dann wieder toString() Experiment. 

### Ohne Optinomic-Felder
Ich habe sehr lange damit "gespielt" und auch eine Lösung gefunden. **DOCH** wir würden die Reihenfolge der Felder verlieren, was wiederum sehr schlecht wäre.  Dies ist ein Javascript Problem:  

> JavaScript objects are unordered by definition ([see the ECMAScript Language Specification, section 8.6](http://www.ecma-international.org/publications/standards/Ecma-262.htm)). The language specification doesn't even guarantee that, if you iterate over the properties of an object twice in succession, they'll come out in the same order the second time.

Entsprechend wird dieses Feature nicht umgesetzt.  Doch sobald wir eine Lösung bzgl. `.csv` Extension (https://github.com/Optinomic/apps/issues/74) gefunden haben - öffnen sich die Files ja direkt in Excel.  Dort Können dann einfach die `optinomic_*` Felder gelöscht werden.
