### ISSUE TITLE
Grafik  ::   Profildarstellung

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#99]
## Grundidee

![img_20170310_122922](https://cloud.githubusercontent.com/assets/2470873/23793815/5ee42c56-058d-11e7-889a-4231ffec5c51.jpg)

### Grafik-Start

Links und Rechts Texte mit jeweils Zahlenbeschriftung.

**Texte:**
```JSON
{
  "left_title": "Text",
  "left_test": "Eine Beschreibung",
  "right_title": "Text",
  "right_test": "Eine Beschreibung"
}
```

### Bewertungen

**Options:**
```JSON
[{
  "range_start": -999,
  "range_stop": -2,
  "color": "#FFEBEE"
},{
  "range_start": -1,
  "range_stop": 1,
  "color": "#E8F5E9"
},{
  "range_start": 2,
  "range_stop": 999,
  "color": "#FFEBEE"
}]
```

### Messzeitpunkte
Eine Profil-Line pro Messung. Ein/Ausschaltbar.

### Klinikstichprobe
Feauture
Auswahl |  Default:  Gemäss "letzter" Messung.

**Comment by ottigerb** [comment]
Eine Version 0.0.1  von `<optinomic-chart-profile>` kann hier angeschaut werden:

http://demo.optinomic.org/api/#/patient/1/stay/144/app/org.optinomic.apps.polymer_cdn
http://demo.optinomic.org/api/#/patient/387/stay/43/app/org.optinomic.apps.polymer_cdn


**ToDo:**
- [x] Normstichproben integrieren.
- [x] Tooltip für Skalenbeschriftung.
- [x] Sonderfall-Handling: Keine links/rechts texte vorhanden.
- [x] Fix Geringe/Starke Ausprägung | Überlappung.
- [ ] Allenfalls eine Detaildarstellung:  Konkrete Werte der Messungen, Rangebeschreibungen etc.

**Comment by schoenenb** [comment]
Brauchst du zu der Anordnung der Beschriftungen noch so "Word-Vorlagen", oder hat sich das jetzt erledigt mit der Profildarstellung?

**Comment by ottigerb** [comment]
Wordvorlage ist m.E. nicht mehr nötig. Ich erstelle bei Gelegenheit eine "webcomponent" page, damit live mit allen Varianten getestet werden kann. Z.B. Wenn keine links/rechts Texte vorhanden sind etc. etc.  Schaut Euch doch schon mal die Grafiken an.  Feedback ist willkommen - auch bzgl. den [offenen ToDo's](https://github.com/Optinomic/apps/issues/99#issuecomment-287292255).

**Comment by schoenenb** [comment]
- [ ] Text unterhalb Skalenbeschriftung ermöglichen?

**Comment by ottigerb** [comment]
> Text unterhalb Skalenbeschriftung ermöglichen?

Was heisst das?  Die Zahlen -3 ... 0 ... +3?    Die Skalenbeschriftung `sub_left` stelle ich mir als Tooltip für Skalenbeschriftung vor.

**Comment by schoenenb** [comment]
Ahso, nein, ich  meinte den Text unterhalb des Subskalentitels (hier kaum lesbar)
![image](https://cloud.githubusercontent.com/assets/15833792/24046513/15b0b5fe-0b23-11e7-9ed2-9d988c0d93e6.png)

Tooltip heisst, dass es nur angezeigt wird, wenn man mit der Maus über den Skalentitel fährt, oder nicht?

**Comment by ottigerb** [comment]
Ja, hätte ich gedacht.  Wir können den Text schon darstellen, dann müsste die item_height jedoch wohl etwas höher ausfallen.  Arbeite weiter.

**Comment by ottigerb** [comment]
![bildschirmfoto 2017-03-17 um 16 51 00](https://cloud.githubusercontent.com/assets/2470873/24051324/04ae5a22-0b32-11e7-933e-90feba968513.png)

Dies wäre möglich. Ich bin mir unsicher, ob dies "gut" ist - m.E. sollten wir doch mit "mouse-over" arbeiten. Oder wie denkt ihr?

**Comment by SonjaKaufmann** [comment]
Lieber Beat,
grundsätzlich gefällt es mir so sehr gut. Finde es eine tolle Idee die Punkte noch zusätzlich einzufärben. Würde dann für die Linien allerdings Grautöne wählen, aber das ist ja sicher kein Problem.
Bei Tooltipp frage ich mich, wie dann der Ausdruck aussehen würde, denn da hätte ich gerne die Unterbeschreibung drauf. Finde so sind wir deutlich kompakter geworden auch ohne Tooltipp. Finde bei diesem Bogen könnten wir den Skalentitel links stehen haben und auf der rechten Seite könnten wir nur die Unterbeschreibungen stehen lassen. So sparen wir dann nochmal die Überschriftszeile. Nehme an, dass der grüne Hintergrund im Beispiel bis 1.5 geht und nicht bis 1 ist ein Test oder bzw. man kann es einstellen. und auch das die Reihenfolge wieder andersherum kommt und das bei Ängstlichkeit rechts GSI steht ist nur, weil es ja nur eine Demo ist.
Ach so finde ich es echt schön!
Zu deinen Punkten: Ja die klinischen Normstichproben sollten als Hintergrund integriert werden, weiss nicht genau was da deine Frage ist.
Tooltipp: schon geschrieben, von mir aus eher nein.
Sonderfallhandling: was für Sonderfälle meinst Du?
Fixe Ausprägungsgrenzen: Wenn die variabel sein können, wäre natürlich besser, aber sonst müssten wir sie beim Maximum definieren,

**Comment by SonjaKaufmann** [comment]
Habe falsches Wort verwendet. meinte wohl mouse-over immer wenn ich Tool-Tipp geschreiben habe. Ist hat eine eigene Sprache :-)

**Comment by ottigerb** [comment]
Danke für das Feedback.  Ich denke ich habe mittlerweile eine gute Vorstellung der Grafik. Werde alle Möglichkeiten so spezifizieren, dass diese je nach Wunsch ein- resp. ausgeschaltet werden können.

**Comment by SonjaKaufmann** [comment]
Hört sich traumhaft an

**Comment by ottigerb** [comment]
## Webcomponents
Wir können nun `webcomponents` einsetzen!  YES!  =>  Schnelle Apps und wohl auch viel leichter für Nora oder weitere Optinomic-App-Developers.  

Um einen Eindruck zu erhalten - wie "einfach" dies nun ist - check:
[org.optinomic.apps.polymer_cli](https://github.com/Optinomic/apps/tree/master/org.optinomic.apps.polymer_cli)

Es stehen bereits optinomic elemente zur Verfügung, welche jeweils auf [Optinomic/polymer-cdn](https://github.com/Optinomic/polymer-cdn/tree/master/lib) publiziert werden. Dies wird dann jeweils via cdn.rawgit verteilt. Entsprechend ist die Angabe von [basepath](https://github.com/Optinomic/apps/blob/master/org.optinomic.apps.polymer_cli/definitions/basepath) nötig.

Hier weiterführende Links zur Info:

1. [Webcomponents](https://www.webcomponents.org/) 
2. [Polymer](https://www.polymer-project.org/1.0/docs/devguide/feature-overview)


## optinomic-chart-profile
Back to topic :: So sehen die ersten Grafiken nun aus:

### BSCL: Ohne Skalen-Beschreibung
![bildschirmfoto 2017-04-07 um 22 56 46](https://cloud.githubusercontent.com/assets/2470873/24820102/b053cc48-1be7-11e7-8bd2-1bfbd2b85a05.png)

### BSCL: Mit Skalen-Beschreibung
![bildschirmfoto 2017-04-07 um 22 58 53](https://cloud.githubusercontent.com/assets/2470873/24820104/b056aa9e-1be7-11e7-9b20-6040274cbd6d.png)

### BDI
Funktioniert auch mit "einfachen" Scores:
![bildschirmfoto 2017-04-07 um 22 56 55](https://cloud.githubusercontent.com/assets/2470873/24820103/b0542f08-1be7-11e7-9c1a-89792b77666b.png)


Wir haben nun folgende Chart-Options:
```JAVASCRIPT
var options = {
    "min": "auto",
    "max": "auto",
    "item_height": 50,
    "item_text_left": 100,
    "item_text_right": 120,
    "color_grid": "#9E9E9E",
    "color_clinic_sample": "#673AB7",
    "show_baseline": true,
    "show_scale_text": true,
    "show_score_vertical_line": false,
    "show_score_profile_line": true,
    "show_score_circles": true,
    "show_settings_block": true,
    "range_alpha": 0.1,
    "vertical_grid_every_x": 1,
    "response_title_path": "calculation.info.mz.mz_typ",
    "response_date_path": "calculation.info.filled"
};
```
#### Details
| Property  |  Description  |
|:---:|---|
| __min__ | "auto" will find the min/max automatically for you. You can also hardcode the min or max by setting it as a number. _Default: "auto"_ |
| __max__ | "auto" will find the min/max automatically for you. You can also hardcode the min or max by setting it as a number. _Default: "auto"_ |
| __item_height__ | The height (px) of every scale from scales. _Default: 50_ |
| __show_settings_block__ | Should the elemet render the Settings-Tab? _Default: True_ |


## Live :: Beispiele 
http://demo.optinomic.org/api/#/patient/1/stay/144/app/org.optinomic.apps.polymer_cli
http://demo.optinomic.org/api/#/patient/387/stay/43/app/org.optinomic.apps.polymer_cli

**Comment by SonjaKaufmann** [comment]
Hey Ho

das sieht richtig genial aus! Vor allem der BDI und der erste BSCL sieht super aus. Ach das gefällt mir richtig gut. Denke Mal ist zur Demo und Reihenfolge und Farben spielen noch nicht so eine Rolle! Aber diese Graphiken versüssen mir den Montag-Morgen ungemein. Ach ist das schön :-) 
So habe ich mit den BDI immer gewünscht. 
Könnte man beim BDI auch minimal, leicht, mittel, schwer auch noch unter die Graphik schreiben und die Interpretation dafür weglassen?
Beim BSCL gefällt mir die Grphik wo es wirklich eine Linie ist und die Punkte nicht noch Balken haben und die Graphik mit der ausführlichen Beschriftung, also eigentlich wäre der Zusammenschnitt aus den Beiden optimal. Geht das? 
Und sind die Graphiken jetzt erstmal nur als App-Graphik so möglich oder sind die auch so als Pdf-Versionen umsetzbar? 
Auf jeden Fall verleihe ich schon Mal den Red Dot-Design-Preis für die Demos!

**Comment by ottigerb** [comment]
😃    Freut mich, wenn's gefällt. Yes!  

**Reihenfolge:**  Die Reihenfolge / Texte der Skalen kann [hier](https://github.com/Optinomic/apps/blob/master/org.optinomic.apps.polymer_cli/elements/view_2.html#L97-L198  ) angepasst werden.

**Farben:** Die Interpretation / Ranges kann z.B. [hier](https://github.com/Optinomic/apps/blob/master/org.optinomic.apps.polymer_cli/elements/view_2.html#L199-L215) angepasst werden. 

**Zusammenzug | Balken**:  Ja, das geht. Jede `<optinomic-chart-profile>` hat ein eigenes `options` Attribut, welches [hier](https://github.com/Optinomic/apps/blob/master/org.optinomic.apps.polymer_cli/elements/view_2.html#L53-L70) angepasst werden kann. Wenn also z.B. die vertikale Linie nicht dargestellt werden soll:  `show_score_vertical_line: false`.  `response_title_path` gibt an, welchen Text die Messung erhält. 

**BDI:** minimal, leicht, mittel, schwer wird unter dem Messungen-Tab dargestellt.   Welcher Text / Datum pro Messung dargestellt wird lässt sich [hier](https://github.com/Optinomic/apps/blob/master/org.optinomic.apps.polymer_cli/elements/view.html#L226-L227) anpassen. Vgl.: http://demo.optinomic.org/api/#/patient/1/stay/144/app/org.optinomic.apps.polymer_cli 
![bildschirmfoto 2017-04-10 um 10 04 26](https://cloud.githubusercontent.com/assets/2470873/24851739/2402ed60-1dd5-11e7-83bc-d02a248075fd.png)


**PDF:**  Ja, dies kann so auch als PDF umgesetzt werden. Mittlerweile können PDF-Charts auch Text darstellen - z.B. den Score als Zahl.


### Anpassen
=>  Du kannst gerne die Reihenfolge / Texte anpassen.  Dazu lediglich die entsprechenden Stellen kopieren - anpassen und hier publizieren.  Nora kann sowas direkt via "commit" anpassen.

z.B.:
```JSON
{
                    "min": -4,
                    "max": "auto",
                    "item_height": 75,
                    "item_text_left": 0,
                    "item_text_right": 285,
                    "color_grid": "#9E9E9E",
                    "color_clinic_sample": "#673AB7",
                    "show_baseline": true,
                    "show_scale_text": true,
                    "show_score_vertical_line": false,
                    "show_score_profile_line": true,
                    "show_score_circles": true,
                    "range_alpha": 0.1,
                    "vertical_grid_every_x": 1,
                    "response_title_path": "calculation.info.mz.mz_typ",
                    "response_date_path": "calculation.info.filled"
}
```

**Comment by SonjaKaufmann** [comment]
Können wir das schliessen?
